name: Patch release to NPM

on: 
  workflow_dispatch:

jobs:
  npm-release-major:
    uses: mateusz1913/react-native-avoid-softinput/.github/workflows/npm-release-template.yml@main
    with:
      increment: patch
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
